=== damianac/poslovna-inf/app/data/mt103.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            targetNamespace="https://github.com/JerSefJeTu/PoslovnaBanka/mt103"
            xmlns="https://github.com/JerSefJeTu/PoslovnaBanka/mt103"
            xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
    
    <xsd:element name="mt103">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="duznik" type="Klijent"/>
                <xsd:element name="poverilac" type="Klijent"/>
                <xsd:element name="nalog" type="Nalog"/>
                <xsd:element name="uplata" type="Uplata"/>
            </xsd:sequence>
            <xsd:attribute name="idPoruke" type="xsd:positiveInteger"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="Uplata">
        <xsd:sequence>
            <xsd:element name="zaduzenje" type="ZO"/>
            <xsd:element name="odobrenje" type="ZO"/>
            <xsd:element name="iznos" type="xsd:integer"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="ZO">
        <xsd:sequence>
            <xsd:element name="broj_racuna" type="Racun"/>
            <xsd:element name="broj_modela" type="xsd:int"/>
            <xsd:element name="poziv_na_broj">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[0-9]+(\-[0-9]+)*"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Nalog">
        <xsd:sequence>
            <xsd:element name="svrha_placanja" type="xsd:string"/>
            <xsd:element name="valuta">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="datum" type="Datum"/>
                        <xsd:element name="sifra" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="datum" type="Datum"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:simpleType name="Datum">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{4}\."/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="Klijent">
        <xsd:sequence>
            <xsd:element name="banka">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="swift" type="swift"/>
                        <xsd:element name="broj_racuna" type="Racun"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="klijent" type="TipLica">
                <xsd:alternative test="@tip='fizicko_lice'" type="FizickoLice"/>
                <xsd:alternative test="@tip='pravno_lice'" type="PravnoLice"/>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="swift">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([a-z|A-Z|0-9]{11})|([a-z|A-Z|0-9]{8})"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="TipLica">
        <xsd:attribute name="tip"/>
    </xsd:complexType>
    
    <xsd:complexType name="FizickoLice">
        <xsd:complexContent>
            <xsd:extension base="TipLica">
                <xsd:sequence>
                    <xsd:element name="ime" type="xsd:string"/>
                    <xsd:element name="prezime" type="xsd:string"/>
                    <xsd:element name="adresa" type="Adresa"/>
                </xsd:sequence>
            </xsd:extension>    
        </xsd:complexContent>
    </xsd:complexType>
    
    <xsd:complexType name="PravnoLice">
        <xsd:complexContent>
            <xsd:extension base="TipLica">
                <xsd:sequence>
                    <xsd:element name="naziv" type="xsd:string"/>
                    <xsd:element name="adresa" type="Adresa"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    
    <xsd:complexType name="Adresa">
        <xsd:sequence>
            <xsd:element name="ulica" type="xsd:string"/>
            <xsd:element name="mesto" type="Mesto"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:simpleType name="KucniBroj">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[1-9][0-9]*[a-z|A-Z]?"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="Mesto" mixed="true">
        <xsd:attribute name="pb" type="PostanskiBroj" use="optional"/>
    </xsd:complexType>
    
    <xsd:simpleType name="PostanskiBroj">
        <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="10000"/>
            <xsd:maxInclusive value="40000"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="Racun">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[1-9][0-9]{2}-[0-9]{13}-[0-9]{2}"/>
        </xsd:restriction>
    </xsd:simpleType>
    
</xsd:schema>

=== damianac/poslovna-inf/app/data/mt103.xml
<?xml version="1.0" encoding="UTF-8"?>
<mt103 idPoruke="1" xmlns="https://github.com/JerSefJeTu/PoslovnaBanka/mt103"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/JerSefJeTu/PoslovnaBanka/mt103 mt103.xsd">
    <duznik>
        <banka>
            <swift>98765432</swift>
            <broj_racuna>123-0000456789123-13</broj_racuna>
        </banka>
        <klijent tip="fizicko_lice">
            <ime>Stefan</ime>
            <prezime>Kajkut</prezime>
            <adresa>
                <ulica>Frana Supila</ulica>
                <mesto pb="78000">Banja Luka</mesto>
            </adresa>
        </klijent>
    </duznik>
    <poverilac>
        <banka>
            <swift>123ABCDE</swift>
            <broj_racuna>987-1234567890000-13</broj_racuna>
        </banka>
        <klijent tip="pravno_lice">
            <naziv>FTN</naziv>
            <adresa>
                <ulica>Trg Dositeja Obradovica</ulica>
                <mesto pb="21000">Novi Sad</mesto>
            </adresa>
        </klijent>
    </poverilac>
    <nalog>
        <svrha_placanja>Uplata skolarine</svrha_placanja>
        <valuta>
            <datum>29.03.2015.</datum>
            <sifra>RSD</sifra>
        </valuta>
        <datum>29.03.2017.</datum>
    </nalog>
    <uplata>
        <zaduzenje>
            <broj_racuna>567-1000002345566-55</broj_racuna>
            <broj_modela>13241</broj_modela>
            <poziv_na_broj>72187</poziv_na_broj>
        </zaduzenje>
        <odobrenje>
            <broj_racuna>567-1234550000066-55</broj_racuna>
            <broj_modela>13241</broj_modela>
            <poziv_na_broj>72187</poziv_na_broj>
        </odobrenje>
        <iznos>5000</iznos>
    </uplata>
</mt103>
